"""Public contract and runtime models for the kernel."""

from .contracts import (
    ActionHashSpec,
    ActionIntent,
    ActionSpec,
    AudienceRef,
    CorrelationRef,
    DigestSpec,
    EvidenceRef,
    ExecutionAnchor,
    PCCB,
    PartyRef,
    Receipt,
    Refusal,
    ScopeSpec,
    SignatureSpec,
    TargetRef,
    TenantRef,
    Violation,
)
from .evidence import EVIDENCE_TYPE_RECEIPT, receipt_evidence_ref
from .execution import (
    ALLOWED_EXECUTION_STATE_TRANSITIONS,
    TERMINAL_EXECUTION_STATES,
    ExecutionState,
    ExecutionStateTransitionError,
    can_transition_execution_state,
    is_terminal_execution_state,
    validate_execution_state_path,
)
from .invoice_payment import (
    InvoicePaymentReconciliationState,
    InvoiceRecord,
    PayeeEnrollment,
    PaymentBatchRecord,
    PaymentExecutionRecord,
    PaymentReconciliationRecord,
)
from .intent_record import (
    BlastRadiusLimit,
    IntentBoundaries,
    IntentRecord,
    IntentRecordDecision,
    IntentRecordEvidenceState,
    IntentRecordProofState,
    build_intent_record,
)
from .policy_bundle import PolicyBundle, PolicyBundleRule
from .runtime import (
    AdmissionResult,
    DynamicContextInput,
    ExecutionResult,
    PolicyDecision,
    PolicyOutcome,
    ProtectedExecutionRequest,
    RuleEvaluation,
)
from .serialization import (
    ARTIFACT_HASH_ALGORITHM,
    ARTIFACT_HASH_CANONICALIZATION,
    artifact_payload,
    build_artifact_digest,
    canonicalize_artifact_bytes,
    canonicalize_artifact_json,
    sha256_artifact_hex,
)

__all__ = [
    "ActionHashSpec",
    "ActionIntent",
    "ActionSpec",
    "AdmissionResult",
    "AudienceRef",
    "ARTIFACT_HASH_ALGORITHM",
    "ARTIFACT_HASH_CANONICALIZATION",
    "CorrelationRef",
    "DigestSpec",
    "DynamicContextInput",
    "EVIDENCE_TYPE_RECEIPT",
    "EvidenceRef",
    "ExecutionAnchor",
    "ExecutionState",
    "ExecutionStateTransitionError",
    "ExecutionResult",
    "InvoicePaymentReconciliationState",
    "InvoiceRecord",
    "IntentBoundaries",
    "IntentRecord",
    "IntentRecordDecision",
    "IntentRecordEvidenceState",
    "IntentRecordProofState",
    "BlastRadiusLimit",
    "PCCB",
    "PayeeEnrollment",
    "PartyRef",
    "PaymentBatchRecord",
    "PaymentExecutionRecord",
    "PaymentReconciliationRecord",
    "PolicyBundle",
    "PolicyDecision",
    "PolicyBundleRule",
    "PolicyOutcome",
    "ProtectedExecutionRequest",
    "Receipt",
    "Refusal",
    "RuleEvaluation",
    "ScopeSpec",
    "SignatureSpec",
    "TargetRef",
    "TenantRef",
    "TERMINAL_EXECUTION_STATES",
    "Violation",
    "ALLOWED_EXECUTION_STATE_TRANSITIONS",
    "artifact_payload",
    "build_artifact_digest",
    "build_intent_record",
    "can_transition_execution_state",
    "canonicalize_artifact_bytes",
    "canonicalize_artifact_json",
    "is_terminal_execution_state",
    "receipt_evidence_ref",
    "sha256_artifact_hex",
    "validate_execution_state_path",
]
