#!/usr/bin/env bash
# OWNER-ACTIONS.md A1-A5 as one script. Run as an Actenon org admin with the GitHub CLI:
#   gh auth login            # an account with admin on the five repositories
#   bash apply-owner-actions.sh            # dry run: prints every API call
#   APPLY=1 bash apply-owner-actions.sh    # applies them
#
# It does NOT do A6-A10 (PyPI trusted publishers, npm/crates tokens, the signed conformance tag,
# advisories): those need registry accounts or a signing key and are listed at the end.
# Environment names and tag patterns are the ones the publish workflows declare
# (`environment: pypi` / `environment: npm`, `on.push.tags`), read from the candidate PR heads.
set -euo pipefail
ORG=Actenon
HERE="$(cd "$(dirname "$0")" && pwd)"
run() { if [ "${APPLY:-0}" = 1 ]; then "$@"; else printf 'DRY-RUN:'; printf ' %q' "$@"; echo; fi; }

REVIEWER_ID="${REVIEWER_ID:-$(gh api user -q .id)}"   # required reviewer for the pypi/npm environments

# A1: Permit workflows disabled for inactivity (6 of its 8 required checks never ran on the candidate).
for w in ci.yml link-check.yml protocol-drift.yml version-coherence.yml actenon-scan.yml; do
  run gh workflow enable "$w" -R "$ORG/actenon-permit"
done
# A2: sdk-go's actenon-scan workflow (informational, not required).
run gh workflow enable actenon-scan.yml -R "$ORG/sdk-go"

# A3: branch protection on main with exactly the required checks of .github/required-checks.json
# (payloads generated by each repo's `scripts/release_gate.py print-protection`).
# The generated payloads ask for 1 approving review with enforce_admins. Every repository has a single
# collaborator (rossbuckley1990-hash, admin; GitHub API 2026-10-03), and GitHub does not let a PR author
# approve their own PR, so that combination would make every PR unmergeable. REQUIRED_REVIEWS (default 0)
# overrides only the review count; the required checks and enforce_admins stay as generated, and the human
# gate before any upload is the pypi/npm environment reviewer (A5). Set REQUIRED_REVIEWS=1 once a second
# maintainer exists.
REQUIRED_REVIEWS="${REQUIRED_REVIEWS:-0}"
for r in actenon-protocol actenon-kernel sdk-go sdk-rust actenon-permit; do
  payload=$(python3 - "$HERE/branch-protection-$r.json" "$REQUIRED_REVIEWS" <<'PY'
import json, sys
p = json.load(open(sys.argv[1]))
p["required_pull_request_reviews"]["required_approving_review_count"] = int(sys.argv[2])
print(json.dumps(p))
PY
)
  run gh api -X PUT "repos/$ORG/$r/branches/main/protection" --input - <<<"$payload"
done

# A4: tag rulesets: only repository admins may create, move or delete release tags.
tag_ruleset() {  # repo, then tag patterns
  local repo=$1; shift
  local includes; includes=$(printf '"refs/tags/%s",' "$@"); includes="[${includes%,}]"
  run gh api -X POST "repos/$ORG/$repo/rulesets" --input - <<EOF
{"name": "release tags", "target": "tag", "enforcement": "active",
 "conditions": {"ref_name": {"include": $includes, "exclude": []}},
 "bypass_actors": [{"actor_id": 5, "actor_type": "RepositoryRole", "bypass_mode": "always"}],
 "rules": [{"type": "creation"}, {"type": "update"}, {"type": "deletion"}]}
EOF
}
tag_ruleset actenon-protocol 'v*' 'ts-types-v*' 'ts-runtime-v*'
tag_ruleset actenon-kernel 'v*' 'verifier-sdk-v*' 'conformance-v*'
tag_ruleset sdk-go 'v*'
tag_ruleset sdk-rust 'v*'
tag_ruleset actenon-permit 'v*' 'ts-sdk-v*'

# A5: deployment environments with a required reviewer, deployable only from release tags.
environment() {  # repo, env, tag patterns
  local repo=$1 env=$2; shift 2
  run gh api -X PUT "repos/$ORG/$repo/environments/$env" --input - <<EOF
{"reviewers": [{"type": "User", "id": $REVIEWER_ID}],
 "deployment_branch_policy": {"protected_branches": false, "custom_branch_policies": true}}
EOF
  for pat in "$@"; do
    run gh api -X POST "repos/$ORG/$repo/environments/$env/deployment-branch-policies" -f name="$pat" -f type=tag
  done
}
environment actenon-protocol pypi 'v*'
environment actenon-protocol npm 'ts-types-v*' 'ts-runtime-v*'
environment actenon-kernel pypi 'v*'
environment actenon-kernel npm 'verifier-sdk-v*'
environment actenon-permit pypi 'v*'
environment actenon-permit npm 'ts-sdk-v*'

cat <<'EOF'

Remaining owner actions this script cannot do (OWNER-ACTIONS.md):
  A6  pypi.org -> actenon-protocol, actenon-kernel, actenon-permit -> Publishing -> Add GitHub publisher
      (owner Actenon, that repository, workflow publish.yml, environment pypi)
  A7  environment secret NPM_TOKEN_ACTENON (environment npm) in actenon-protocol, actenon-kernel, actenon-permit
      (gh secret set NPM_TOKEN_ACTENON --env npm -R Actenon/<repo>)
  A8  gh secret set CARGO_REGISTRY_TOKEN -R Actenon/sdk-rust
  A9  git tag -s conformance-v1.1.0 <kernel merge commit> -m "Actenon Conformance 1.1.0" && git push origin conformance-v1.1.0
      (at release-graph step 2, with a signing key GitHub verifies)
  A10 private advisories: publish each only after its fixed version is installable
EOF
